### ISSUE TITLE
Option Notify

### ISSUE THREAD

**Issue by kosirm** [mloberg/jekyll-browsersync#1]
Hi, thank you for sharing this great plugin! I'm looking for a way to disable browsersync pupup
with browsersync option: [https://www.browsersync.io/docs/options/#option-notify](https://www.browsersync.io/docs/options/#option-notify)
but I don't know how to include this with your plugin.
Thanks for any hint!

**Comment by ivorisoutdoors** [comment]
Currently I only support a subset of all options available to BrowserSync. It was written with my use case in mind.

It could be updated to accept BrowserSync options. I could update it this weekend or if you would like to submit a Pull Request, I would love to accept that

**Comment by kosirm** [comment]
Thanks, that would be great if you could update it to accept BrowserSync options! Unfortunately I never wrote nothing with ruby, I just use jekyll. BR

**Comment by ivorisoutdoors** [comment]
You should be able to pass the notify option as such:

    $ jekyll browsersync -- --no-notify

I'm working on releasing _v0.1.0_, which will include this change.

__Edit__: Released: https://rubygems.org/gems/jekyll-browsersync/versions/0.1.0

**Comment by kosirm** [comment]
Thanks so much! I'm trying to make it work...
Until now I was serving my pages locally like this:
No browser sync: jekyll serve --host $IP --port $PORT --baseurl ''
With browsersync: jekyll bs --host $IP --port $PORT --baseurl ''

How could I serve my pages with browsersync and no-notify option? Can I add no-notify option to _config.yml maybe?
I'm new to jekyll. Thanks again for your work!

**Comment by ivorisoutdoors** [comment]
Everything after `--` will be passed directly to the browsersync executable.

    $ jekyll bs --host $IP --port $PORT --baseurl '' -- --no-notify

**Comment by kosirm** [comment]
🥇 Working like a charm! Thank you!
